[project]
name = "pythonbootcampudemy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "heroes>=1.0.2",
    "mypy>=1.11",
    "prettytable>=3.16.0",
    "ruff>=0.13.0",
]
